### Query Pexels
GET https://api.pexels.com/v1/search?query=pizza
Authorization: {{$dotenv KEY_PEXELS}}

### Query Unsplash
GET https://api.unsplash.com/search/photos?query=pizza
Authorization: {{$dotenv KEY_UNSPLASH}}

### Query Pixabay
GET https://pixabay.com/api/?key={{$dotenv KEY_PIXABAY}}&q=pizza


### Add a new user
POST http://localhost:3000/api/user/add
Content-Type: application/json

{
    "user": {
        "username": "testUser",
        "password": "myTestPw"
    }
}


### Check if an user exists
POST http://localhost:3000/api/user/check
Content-Type: application/json

{
    "user": {
        "username": "testUser74"
    }
}


### Login an user
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "user": {
        "username": "testUser",
        "password": "myTestPw"
    }
}


### Logout an user
POST http://localhost:3000/api/user/logout
Content-Type: application/json

{
}


### Validate login
POST http://localhost:3000/api/user/checklogin
Content-Type: application/json

{
    "bla": "blubb"
}


### Create new collection
POST http://localhost:3000/api/collections/add
Content-Type: application/json

{
    "collectionName": "myCollection3"
}


### Get all user's collection
GET http://localhost:3000/api/collections
Content-Type: application/json


### Delete a collection
DELETE http://localhost:3000/api/collections/delete
Content-Type: application/json

{
    "collectionId": "6151cb9927f25d09f32feee2"
}


### Add an image to a collection
POST http://localhost:3000/api/images/add
Content-Type: application/json

{
    "collectionId": "6151de2520d8e8faaf03b768",
    "image":
    {
        "id":"uu9tAl8WR3DI",
        "title":"low-angle photography coconut trees during golden hour",
        "width":4000,
        "height":6000,
        "urlSource":"https://unsplash.com/photos/u9tAl8WR3DI",
        "author":"Jordan McQueen",
        "urlAuthor":"https://unsplash.com/@jordanfmcqueen",
        "src":"https://images.unsplash.com/photo-1535392432937-a27c36ec07b5?ixid=MnwyNTY3MDF8MHwxfHNlYXJjaHwxfHxwYWxtJTIwYmVhY2h8ZW58MHx8fHwxNjMyMzA1NDc3&ixlib=rb-1.2.1",
        "preview":"https://images.unsplash.com/photo-1535392432937-a27c36ec07b5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwyNTY3MDF8MHwxfHNlYXJjaHwxfHxwYWxtJTIwYmVhY2h8ZW58MHx8fHwxNjMyMzA1NDc3&ixlib=rb-1.2.1&q=80&w=1080",
        "thumbnail":"https://images.unsplash.com/photo-1535392432937-a27c36ec07b5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwyNTY3MDF8MHwxfHNlYXJjaHwxfHxwYWxtJTIwYmVhY2h8ZW58MHx8fHwxNjMyMzA1NDc3&ixlib=rb-1.2.1&q=80&w=200",
        "thumbnailWidth":200,
        "thumbnailHeight":120000,
        "createdAt":"2018-08-27T13:54:40-04:00",
        "likes":2891,
        "aspectRatio":"2 : 3",
        "api":"unsplash",
        "score":10000
    }
}
