### Query Pexels
GET https://api.pexels.com/v1/search?query=pizza
Authorization: {{$dotenv KEY_PEXELS}}

### Query Unsplash
GET https://api.unsplash.com/search/photos?query=pizza
Authorization: {{$dotenv KEY_UNSPLASH}}

### Query Pixabay
GET https://pixabay.com/api/?key={{$dotenv KEY_PIXABAY}}&q=pizza


### Add a new user
POST http://localhost:3000/api/user/add
Content-Type: application/json

{
    "username": "testUser",
    "password": "myTestPw"
}